### ISSUE TITLE
[FE] トップページでのカードの表示方法を検討して実装する

### ISSUE THREAD

**Issue by detianitatibs** [detianitatibs/shanari-shanari-fe#9]
# 何がしたいか
これまでの過程でフロントエンドは開発したので、実際にTechnologyやBlogのコンテンツをDBなどリソースを意識して取得できるようにバックエンドのロジックを実装する。  
バックエンドコンテナが必要かどうかは試しながら判断する。不要ならFEのみでまずは実装する。  
=> 結論として、まずはファイルベースで設計しパフォーマンスが悪くなってきたらDBを検討する

# 設計方針
- `public`ディレクトリ配下に`contents`ディレクトリを作成する
- `contents`ディレクトリ配下にコンテンツをディレクトリとして作成する
  - 例えば技術ページの`tech`やブログの`blog`など
- 各コンテンツディレクトリ直下に`ContentConf.yaml`を作成する
  - `ContentConf.yaml`は下の(*1)のような構成とする
- 各ディレクトリ直下に`YYYY/MM/DD/通し番号`のフォルダを準備しその配下にカード毎の`CardConf.yaml`を作成する
  - `CardConf.yaml`は下の(*2)のような構成とする
  - 各フォルダイメージは下の(*3)のような構成とする

(*1)
```yaml
ContentConf:
  - subject_name: "Technology"
  - abbreviation_name: "tech"
  - priority: 1
```
`priority`は低いほど上位にコンテンツを出す
 
(*2)
```yaml
CardConf:
  - image_path: "./XXX.png"
  - title: "技術1"
  - category: "tech"
  - date: "2024-10-10"
```
`image_path`は省略可能で、その場合はデフォルトアイコン(icon.png)が使われる

(*3)
```
public/
    └ contents/
             ├ tech/
             │     ┝ ContentConf.yaml
             │     └ 2024/
             │          └ 10/
             │               └ 11/
             │                   └ 1/
             |                       └ CardConf.yaml
             └ blog/
                   ┝ ContentConf.yaml
                   └ 2024/
                         └ 09/
                             └ 01/
                                 └ 1/
                                    ┝ CardConf.yaml
                                    ┝ Article.md
                                    └ XXX.png
```
